void command_handler();
void clear_screen_command();
void ls_command();
void lsdir_command();
void rename_command();
void exit_command();
void redirect_command();
void lsdir_command();
void cd_command(int number_of_token);
void strip_string(char** str);
int tokenize_user_input(char* user_input);
void rename_command();
void remove_command();
void move_command();
void copy_command();
void cat_command();
void head_command();
void tail_command();
